APP_VERSION = "v18.6.4k"
APP_VERSION_NAME = "Source Foundation Contract"
APP_BUILD_ID = "v1864k-source-foundation-contract"
APP_BUILD_LABEL = f"{APP_VERSION} - {APP_VERSION_NAME}"

APP_PATCH_NOTES = [
    "Test 1 behandler naa Finansavisen, Oljefond/NBIM og Folketrygdfondet som datakilder/overlays, ikke som raa filer som sendes gjennom hele Test 1-10-flyten.",
    "Folketrygdfondet har nytt importpanel for .xls/.xlsx som bygger institusjonelt eier-overlay til senere tester.",
    "Test 3 viser en aktiv Fortsett med raa input fra Test 2-knapp naar Smart AI-filteret gir 0 funn, slik at Test 4 ikke blir visuelt skjult.",
    "Globale Streamlit-knapper er strammet ned til kompakt hoyde, mindre padding og mindre tekst.",
    "Tickeruttrekk fra Analyseflyt ignorerer naa metadatafelt som raw, score_parts og mangler-felt, slik at de ikke blir falske aksjesymboler i Test 3 og videre.",
    "Pipeline-pakker filtrerer bort ugyldige tickerverdier fra Test 2-10, men lar Dataunderlag fortsatt sende kontrollrapport uten aksjeticker.",
    "Store bla knapper er strammet til normal knappestorrelse globalt, med tekstbrytning for lange handlingsknapper.",
    "Finansavisen-import har bare avhuking for Aktorregister-synk; den dupliserte Synk lagret import-knappen er fjernet.",
    "Smart AI har bare en Kjor Smart AI-utvalg-knapp i selve Smart AI-utvalg-seksjonen; flytbaren viser status og viderevalg.",
    "Analyseunivers forklarer standardverdiene for Top Picks-score og momentum/strength-filter direkte ved sliderne.",
    "Kontrollsenteret viser en egen Testflyt-meny for aktivt steg, slik at relevante paneler/tester ligger samlet uten aa blande inn alt annet som standard.",
    "Smart AI/Top Picks-resultater respekterer valgt maks-antall i stedet for skjulte 10/15-grenser.",
    "Fjernet den doble Start her: 1. Dataunderlag-knappen; Test 1-10-knappene er naa eneste pipeline-hurtigvalg.",
    "Finansavisen-knappene sier eksplisitt Test 2 Marked/rangering og bruker nye widget-nokler slik at gamle Streamlit-knapper ikke henger igjen.",
    "Direkte Test 8-valg fra Finansavisen kan naa velge alle matchede tickere i visningen, ikke et gammelt 20/60-tak.",
    "Alpha Radar-beslutningsvalg kan naa sende alle kandidater i resultatet videre til Beslutningsgrunnlag.",
    "Pipelinebaren kan naa sende raa input videre naar en test har input men 0 funn, slik at flyten ikke stopper i Test 3-8.",
    "Input/output-tall viser effektiv input for Portefoljeanalyse og Paper Trading naar resultatpakken allerede finnes.",
    "Alpha Radar og Early Warning V1 synker naa aktivt steg riktig i hovedflyten naar du bytter sokemotor.",
    "Beslutningsgrunnlag kan sende raa analyseflyt-input videre til Portefoljeanalyse naar vurderingen gir 0 output.",
    "Portefoljeanalyse viser posisjoner i tydelige kolonner med ticker, vekt, type, kategori, sektor, marked og detalj.",
    "Paper Trading viser mottatte kandidater fra Test 9 i en lesbar input-tabell foer simulert handel.",
    "Test 3 viser naa en egen Videre til Test 4-blokk med valg for Smart AI-funn eller raa input fra Test 2.",
    "Send videre til Test 4 ligger ikke lenger i en smal kolonne som kan forsvinne visuelt naar Test 3 har 60 inn og 0 ut.",
    "Finansavisen i Test 1 viser naa Input/Output for handler, matched tickere og valgt/hele dataunderlag.",
    "Finansavisen-knappene sender naa valgte tickere eller hele dataunderlaget til Test 2 Marked/rangering, ikke tilbake til samme Test 1-panel.",
    "Test 2 bruker inputpakken fra Dataunderlag naar den finnes, i stedet for aa ignorere den og hente foerste N fra felles univers.",
    "Direkte sending til Test 8 fra Finansavisen bruker valgt antall tickere i stedet for gammel skjult limit 20.",
    "Dynamiske analyseflyt-slidere nuller naa gamle session-verdier som ligger over ny inputpakke, slik at Test 4 ikke krasjer med 30 > 18.",
    "Test 2, Test 4, Test 7, Test 9 og Alpha/Early Warning har slider-guard mot gamle verdier naar inputpakken blir mindre.",
    "Analyseunivers-tabeller har naa Vis antall rader 10/15/20/30/Alle, med Alle som standard naar pakken er 60 eller mindre.",
    "Smart Universe Picker viser ikke lenger score-/styrke-/1M-/3M-kolonner foer Smart AI faktisk er kjoert.",
    "Smart AI- og Picker-knapper sender valgt maks-antall videre, ikke gamle hardkodede 10/30-grenser.",
    "Eldre Top Picks-kodevei bruker valgt max_count i stedet for hardkodet 15.",
    "Smart AI-tabeller bruker visningsnummer i faktisk sorteringsrekkefolge, slik at gamle rank-tall ikke hopper i venstre kolonne.",
    "Test 3 har naa tydelig Kjor-knapp i flytbaren og en aktiv Fortsett med inputpakken-knapp naar Smart AI-filteret gir 0 output.",
    "Fortsett med inputpakken lagrer Test 3-output som ufiltrert bypass og sender kandidatene videre til Test 4 uten automatisk tung analyse.",
    "Test 3 viser naa Forrige-knapp, tydelig Input/output-status og Send videre til Test 4 i samme flytbar.",
    "Analyseflyt input i Test 3 bruker hele mottatt kandidatpakke som standard og slideren kan ikke gaa over antall kandidater fra Test 2.",
    "Manuell ticker og manuell liste skjules i Test 3 naar valgt modus ikke bruker dem.",
    "Roadmap/detaljstatus i Analyseunivers er midlertidig gjort kompakt for aa hindre stor hvit/tom flate.",
    "Test 3 lagrer naa Smart AI-output som pipeline-pakke og sender den videre til Test 4, slik at Top Picks mottar faktisk input i stedet for 0/0.",
    "Kandidat-slidere for analyseflyt-input laases til faktisk inputpakke, og rangeringsvisning kan velge Topp 10, 15, 20, 30 eller Alle uten aa endre pakken som sendes videre.",
    "Pipeline-service har regresjonstest for hele dataflyten fra Test 1 Dataunderlag til Test 10 Paper Trading.",
    "Steg 1 heter naa 1. Dataunderlag, fordi det samler og kontrollerer underlag foer Test 2 uten aa kjoere analyse.",
    "Analyseflyten har hurtigtaster for Test 1-10, synlig aktivt steg, forrige/neste-knapper og bedre synk mellom aktivt panel og undermeny.",
    "Input/output-visningen forklarer input fra forrige steg og output fra dette steg, og Dataunderlag-output viser kontrollrapport i stedet for tom kandidatvisning.",
    "1. Dataunderlag er datakilde-cockpit med direkte knapper til Finansavisen, Aktoerregister, Oljefond/NBIM og kildestatus.",
    "Test 2 Marked/rangering har Dataunderlag som standard univers, viser om input fra steg 1 er mottatt og forklarer hva universet bruker.",
    "Analyseflyt-statusen er ryddet til en hovedtabell og en lukket detaljvisning, slik at samme stegstatus ikke vises dobbelt.",
    "Pipeline-linjen i Test 2-10 viser naa forrige steg, input/output-status og send-videre-knapp; den gamle midtknappen for aa aapne samme test med standardvalg er fjernet.",
    "Nytt Marked-rom samler marked, chart-valg, gruppering, periode og visning i en terminal-lignende toolbar med Oversikt, Rangering, Heatmap, Regime, Makro og Nyheter.",
    "Oppstarten gaar naa rett til Marked som standard arbeidsflate, mens Start/Pause/Stopp og Global oppdatering skjules bak drift-valg i sidepanelet.",
    "Husk-meg-token lagres i browser storage uten aa bli liggende synlig som remember_token i adresselinjen.",
    "Test 3 Smart AI-filter velger Analyseflyt input automatisk naar Test 2 har sendt kandidater videre, og videre-knapper viser antall kandidater som sendes.",
    "Test 2 Marked/rangering har synlig progress med faser for univers, data/cache, lagring og ferdig kandidatpakke.",
    "Tickerkort bruker felles metadata for firmanavn og har utvidet dekning for blant annet MO/Altria og AKAM/Akamai.",
    "Sidepanelet skiller naa tydeligere mellom vanlig visningsmodus og driftvalg for Start/Stopp/Global.",
    "Finansavisen-panelet kan sende importstatus tilbake til 1. Dataunderlag og hoppe dit, mens direkte snarvei til Beslutningsgrunnlag er merket som Test 8.",
    "Godkjenn og send til Test 2 ligger nederst etter datakildekontroll, ikke oeverst foer brukeren har sett hva som kan kontrolleres.",
    "Paper Trading fyller land, marked, sektor og bransje best-effort for gamle posisjoner/handler og lar posisjoner velges direkte til kjop/salg.",
    "1. Dataunderlag ligger synlig under Marked og signaler med statusrad i AI Kontrollsenter.",
    "Paper Trading sjekker naa aapne posisjoner for stop-loss, take-profit, trailing stop og RSI-exit foer nye BUY-signaler kan overstyre.",
    "Handelsloggen viser land, marked, sektor/bransje, regel, grense, maalt verdi og en kort forklaring paa hvorfor en handel ble gjort eller solgt.",
    "Analyseflyt starter med 1. Dataunderlag og veiviser videre til Test 10 Paper Trading.",
    "Hvert hovedsteg viser input/output-status, anbefalt standardvalg og knapp for aa sende ferdig kandidatpakke videre uten automatisk tung kjoring.",
    "Veiviseren hopper til riktig Kontrollsenter-panel og setter Analyseflyt input der det er relevant, mens selve motorene fortsatt krever eksplisitt Kjor.",
    "Felles markedsvalg er viderefÃ¸rt i AI Kontrollsenter, Top Picks, Smart Universe, banner og Fond/ETF.",
    "Finland, Danmark og Brasil er synlige valg der markedsmotoren brukes, mens Norden samler Norge, Sverige, Finland og Danmark.",
    "Smart Universe-tabeller viser selskap, land, bÃ¸rs, status, score, risiko og forklaring i stedet for bare ticker.",
    "Fond/ETF har marked/region, automatisk benchmark og tydelig melding nÃ¥r pris-/NAV-data mangler.",
    "SmÃ¥ tekster, statusrader og mÃ¸rke tabeller er gjort mer lesbare pÃ¥ PC og mobil.",
    "Paper Trading viser aksjekjÃƒÂ¸p igjen, henter pris/NAV tydeligere og viser gjeldende trading-strategi.",
    "Mobil-login, Smart AI-statuskort og Analyseunivers-oppsett er forbedret for mindre friksjon.",
    "AI Kontrollsenter er gjort tydeligere som hovedarbeidsflate med stÃ¸rre header og aktivt panel.",
    "Apne AI Kontrollsenter-linjen er gjort tydeligere og friskere, og importfeil i Kontrollsenter-header er rettet.",
    "AI Kontrollsenter-valgene er gjort lysere/storre, panelvalg synkroniseres med arbeidsomrade, og Paper Trading nullstiller gammel pris ved tickerbytte.",
    "Paper Trading bruker markedsmotoren til prisforslag/system-confidence og viser posisjonsgevinst/-tap i tydelige blaa/rode kort.",
    "Strategi-test Pro har tryggere kraftig smart-test, tydeligere tidlig stopp og hopper over enkeltkombinasjoner som feiler.",
    "AI Kontrollsenter-valgene er rendret som tydeligere blaa kontrollbokser, og den lille dupliserte toppstripen er fjernet.",
    "P/E vises i Top Picks/hurtigkort i tillegg til detaljanalysen, basert paa forward/trailing P/E fra felles aksjeanalyse.",
    "Learning history skjuler demo-/testtickere fra brukerlisten og viser tolkning av retning, prognosebaand og snittfeil.",
    "Topplinjen er ryddet for sesjonschips som Manuell, Bruker og Husk meg.",
    "Heatmap filtrerer bort gamle AAPL/STB.OL-seeddata og bruker samme filtrerte datasett for tall og visning.",
    "Tekniske kursnivaer viser valuta tydeligere, ORK/ORKLY tolkes som ORK.OL, og chart/legend-spacing er forbedret.",
    "Regime-panelet har markedvalg for USA, Norge, Sverige, Danmark, Finland, Brasil og Norden.",
    "Paper Trading-portefoljen kan brukes som testarena for portefoljeovervaking, kontrollpunkter og AI-forslag.",
    "AI Kontrollsenter har valutavarsler med faste ovre/nedre grenser og Pushover-stotte, for eksempel BRL/NOK.",
    "AI Kontrollsenter har hovedboks-rad, automatisk undermeny, favoritter, sist brukt, sok, arbeidsmodus og paneltellere.",
    "AI Kontrollsenter bruker ren hurtignavigasjon uten skjulte gamle dropdowns, med tydelig Til hovedvalg-knapp.",
    "AI Kontrollsenter er forenklet til hovedbokser og kompakt undermeny, uten automatisk aapnet startpanel.",
    "AI Kontrollsenter bruker stabil radio-basert hovedmeny og undermeny for mindre knekk ved menyvalg.",
    "AI Kontrollsenter-navigasjon unngaar ekstra rerun og hopper over ticker-banneret under aktiv menybruk.",
    "Gamle AAPL/MSFT/NVDA-defaults er fjernet fra Daily Report, Prognose og service-univers, og tester stopper skjult manuell fallback.",
    "Regresjonsvern er utvidet for kildeprioritet, panel-smoke, tung-jobb gating og visuelle statiske guardrails.",
    "Oppstart av Kontrollsenter nuller engangsflagget for tung jobb slik at ticker-banneret ikke forsinker Analyseunivers/preview.",
    "Analyseunivers forklarer tydelig forskjellen mellom tickerliste/univers, preview-cache og scorede Smart AI-kandidater.",
    "AI Kontrollsenter har Alpha Radar som eksplisitt kjoert hypotesemotor for 1-15 mulige aksjecaser paa 1, 3, 6 og 12 maaneder.",
    "Alpha Radar V2 bruker Contrarian / Hidden Potential Score med underdekkethet, vendepunkt, insider/bjellesauer, uvanlig volum, ravare/makro, why-now og crowding-straff.",
    "Alpha Radar har strengere parameterdisiplin med harde borsverdi-gates, presisjonsvalg, lav-data blokkering og tydelige ekskluderingsaarsaker.",
    "Alpha Radar viser scan-progresjon, skiller signal-lupe fra datakilder, markerer gamle resultater naar input endres og kan lagre/eksportere resultat.",
    "Alpha Radar viser manglende faktorgrunnlag som N/A, stopper univershenting ved vanlige menyvalg, har komplett print/Excel-eksport og Early Warning V1.",
    "Early Warning er skilt tydeligere fra Alpha Radar med ferske kildebevis, insider-/bjellesau-spor, nyhetskatalysatorer og Euronext/Norden-notat i rapportene.",
    "Alpha Radar/Early Warning-rapportene viser kildespor med titler, kilder, datoer og lenker der datakilden leverer dette.",
    "Mobilvisning for driftkontroll og Alpha Radar Signal-lupe er strammet inn uten aa flytte tunge jobber ut fra eksplisitte Kjor-knapper.",
    "Alpha Radar og Early Warning bruker felles regelmotor for Signal-lupe, datakilder, laasing, lav-data og overstyringsrekkefolge.",
    "Radar-panelet viser Kjoringsbudsjett / Run Preview med 0 tunge kall ved menyvalg og planlagt kostnad ved Kjor.",
    "Neste GO: hvis appen fortsatt dimmer ved menyvalg, profiler hele Kontrollsenter-renderen og flytt gjenvaerende cache-/statuskall ut bak eksplisitte knapper.",
    "Radar-menyene er strammet: Radar-modus laaser kjerne-signalene, ekstra Signal-lupe er separat, og datakilder folger samme regelmodell.",
    "Insider-modus i Alpha Radar starter naa med Insider/bjellesauer alene; nyheter/resultater blir kun stottevalg hvis bruker legger dem til.",
    "Kontrollsenter avslutter tung-jobb-gaten foer st.stop, slik at Global oppdatering ikke blir hengende igjen og gjor senere menyvalg tunge.",
    "Alpha Radar og Early Warning henter alltid ferskt run-univers ved Kjor, nuller gammel tickerliste og viser markedstelling for univers, skannet, scoret, ekskludert og funn.",
    "Alle/Norden bruker balansert sluttliste: beste funn per marked tas med foer resten fylles etter score, slik at USA ikke kan skjule alle andre markeder uten forklaring.",
    "Funn-grensen er utvidet til 60 for brede univers, og IPO/pre-IPO forklares som separat omraade, ikke som skjult tillegg i 177-universet.",
    "Radarene krever naa konkret nyhets-/makro-/resultatevidens foer faktorer merkes ekte, slik at tomme kildesok ikke gir lik 45.0-katalysator paa alle tickere.",
    "Borsverdi vises med punkt som tusenskille og lokal valuta, med ca. NOK-estimat der valuta ikke er NOK.",
    "Enkeltmarked bruker egen skannegrense i Alpha Radar/Early Warning, Brasil-listen er utvidet, og 177 behandles ikke som fast globalt tak.",
    "Alpha Radar og Early Warning skiller naa Insider fra Bjellesau i scoring, kildespor, CSV, Excel, HTML/PDF og resultatkort.",
    "AI Kontrollsenter har nytt Beslutningsgrunnlag-panel som tar radarfunn videre til manuell Kjop naa/Vent/Unnga-vurdering uten automatisk handel.",
    "Finnhub- og NewsAPI-nokler lastes naa robust fra work_d/.env eller work_d/.env/.env, og radarene viser trygg datakilde-status uten aa vise nokler.",
    "Alpha Radar/Early Warning lar 1, 3, 6 og 12 mnd styre datavinduet for insider, nyheter og earnings, og har egen markedstest for USA/Norden-datakilder.",
    "Datakilde-status viser naa API-nokler i aktivt miljo uten aa hevde at .env mangler, og lange kildefeil komprimeres i kandidatkortene.",
    "AktÃ¸rregister lar deg redigere bjellesauer/institusjoner/insider-watch med alias per marked, og radarene bruker dette til aa merke aktorspor.",
    "Norden/Brasil faar lokale kildediagnostikk-lenker for insider, flagging, borsmeldinger, OAM og katalysator-sok der globale API-er ikke dekker markedet.",
    "Early Warning bruker resultat-/vendepunkt-proxy naar earnings/revisions mangler, og rapportene viser tydeligere datadiagnostikk for tomme felt.",
    "Oljefond Radar kan importere NBIM CSV, finne nye/okte/reduserte/solgte posisjoner og sende NBIM-spor videre til Beslutningsgrunnlag.",
    "Beslutningsgrunnlag har tydeligere knapper: Vurder hele kÃ¸en og TÃ¸m kÃ¸.",
    "NBIM-parseren leser naa ekte eq_YYYYMMDD.csv fra Oljefondet i UTF-16/semikolon-format og matcher selskapsnavn/land mot tickerregisteret.",
    "Tickeruniversene er utvidet for USA, Norge, Sverige, Finland, Danmark og Brasil, og run-preview sier tydelig naar universkilden er mindre enn maks scan.",
    "AktÃ¸rregisteret har import/eksport for CSV/JSON, relevante tickere og NBIM/Oljefondet som aktiv institusjonell aktor.",
    "Radarene kan bruke finans-/offisiell sokelag ved Kjor, med aktornavn, alias, ticker, selskap og marked, uten tunge kall ved menyvalg.",
    "NBIM, finanssok, aktorregister og konkrete insider-/bjellesau-spor sendes videre til Alpha Radar, Early Warning, rapporter og Beslutningsgrunnlag.",
    "Oljefond Radar har prioriterte visninger for topp signaler, storste beholdninger, nye kjop, okninger, reduksjoner med restverdi, solgt ut, ticker-match og land/sektor.",
    "NBIM-tabeller viser markedsverdi med punkt som tusenskille og enhet, og previous/current value oversettes per metric til prosent, aksjer eller valuta.",
    "Oljefond Radar har progress-status fra filventing til ferdig analyse, uten nye nettverkskall eller meny-tungkjÃ¸ring.",
    "NBIM Signal Lab finner overbevisning, akkumulering i svakhet, hoy eierandel, stemmerett-avvik, unmatched verdi, radar-overlap og watchlist-kandidater.",
    "NBIM land-/sektorrotasjon viser inn/ut/blandet, ny verdi, okt verdi, redusert restverdi og tidligere solgt-ut verdi.",
    "Alpha Radar og Early Warning bygger naa en felles Evidence Ledger per ticker med kilde, type, dato, aktor, styrke, lenke og funnet-av.",
    "Nordic Actor/Insider Search lager gratis/offisielle sokelenker for Norden og bruker Aktorregisteret automatisk ved insider-/bjellesau- og nyhetssok.",
    "Run Preview viser kildebudsjett/kildeko med NewsAPI, Finnhub, cache, aktorregister og gratis/offisielle sok foer Kjor.",
    "Aktorregisteret har legg-til, slett-valgte, marked-dropdown, teksttest og Unmatched Workbench for navn som maa kobles til alias.",
    "Aktorregisteret stÃ¸tter flere roller per aktÃ¸r, slik at samme person kan vÃ¦re Bjellesau og Insider watch uten dobbeltregistrering.",
    "Aktorregisteret har sÃ¸k, sortering, hurtigredigering, alias-forslag, duplikatsjekk, tillitsnivÃ¥ og lokal trefflogg per aktÃ¸r.",
    "Radarene tolker aktÃ¸rroller strengere: bjellesau-/institusjonsroller gÃ¥r til bjellesau-score, insider-watch/styre/ledelse gÃ¥r til insider-spor.",
    "Aktorregister-panelet viser tydelig at registeret lagres lokalt, men at navn/alias kan inngÃ¥ i sÃ¸k nÃ¥r bruker trykker KjÃ¸r.",
    "Radarene har harde bevisporter: velges insider/bjellesau og nyheter som kriterier, blir tickere uten konkrete kildespor ekskludert i stedet for Ã¥ fylle topp 30.",
    "AktÃ¸rstyrt sÃ¸k kjÃ¸res fÃ¸rst og kan bruke gratis open web via GDELT/Google News RSS som supplement til NewsAPI, slik at lokale finansnyheter og aktÃ¸rnavn faktisk kan gi treff.",
    "AktÃ¸rregisteret bruker lett tabell pluss enkelt skjema for ny/redigert aktÃ¸r, med flerroller og trefflogg bak knapp for Ã¥ unngÃ¥ tung meny-rendering.",
    "Finansavisen Bjellesauer har egen lokal XLSX-import for 1D/1M/3M/6M/ALLE, deduplisering, periodescoring, rapport, eksport og Aktorregister-synk.",
    "Alpha Radar og Early Warning bruker Finansavisen-snapshot som billig lokalt bjellesau-evidenslag ved Kjor, uten Excel-parse eller nye nettverkskall ved menyvalg.",
    "Norske bjellesau-tickere som NORBIT, Zaptec og Axactor er lagt inn i ticker-/aliasregisteret slik at importerte handler kan treffe radaruniverset.",
    "Finansavisen-importen bruker filnavn og filstorrelse i periodevalg, slik at 1D/1M/3M/6M/ALLE ikke arver gamle valg.",
    "Finansavisen-deduplisering taaler overlappende filer i ulik rekkefolge og beholder alle kildeperioder uten importkrasj.",
    "Finansavisen Bjellesauer ligger under Marked og signaler, og Andre paneler skjules naar ingen reelle restpaneler finnes.",
    "Finansavisen Bjellesauer har lesbar rapportseksjon, print/PDF-HTML, nedlastbar PDF, ticker-match-filter og sending til Beslutningsgrunnlag.",
    "Finansavisen Bjellesauer viser naa aksjedetaljer per dato, person og transaksjonslinje, og rapport/PDF tar med detaljene for viktige aksjer.",
    "Portefoljeanalyse analyserer Paper Trading-portefoljen komplett uten maksposisjon-slider og retter _clamp-krasjen.",
]

def get_app_version():
    return APP_VERSION

def get_app_build_label():
    return APP_BUILD_LABEL

def get_app_version_label():
    return APP_BUILD_LABEL

def get_app_patch_notes():
    return list(APP_PATCH_NOTES)


