APP_VERSION = "v18.6.22"
APP_VERSION_NAME = "Refresh-login uten fastlaast restore"
APP_BUILD_ID = "v18622-auth-restore-fallback"
APP_BUILD_LABEL = f"{APP_VERSION} - {APP_VERSION_NAME}"

APP_PATCH_NOTES = [
    "Refresh-login kan ikke lenger bli stående fast på gjenoppretting; etter restore-forsøk vises innloggingen som fallback.",
    "Refresh med Husk meg får gjenopprette innlogging før login-skjema vises, og remember-token beholdes i URL mens langtidsinnlogging er aktiv.",
    "Særskilt overvåking har egen banneranimasjon, egen lifecycle-kilde og egen signalhistorikk slik at hastighet og logg ikke blandes med hovedbanneret.",
    "Særskilt overvåking har gul nær-grense og Pushover ved rød markør i samme meny som tickerlisten.",
    "Både hovedbannerloggen og særskilt signalhistorikk kan kappes eller tømmes manuelt.",
    "Paper Trading har manuell kurs/NAV for åpne posisjoner når automatisk Close/NAV mangler.",
    "Innkommende paper-hypoteser viser når instrumentet allerede finnes i paper-porteføljen, i stedet for å påstå at det ikke er beholdning.",
    "Særskilt overvåking vises nå som eget banner rett under hovedbanneret når det er aktivert.",
    "Menyen for Særskilt overvåking ligger før Ticker-banner og samler styring, hastighet, tickerliste og fjerning.",
    "Særskilt-banneret bruker samme to-kopi ticker-tape som hovedbanneret, slik at samme hastighet oppleves likere.",
    "AI Kontrollsenter beholder valgt panel ved rerun når panelet fortsatt hører til valgt hovedområde, slik at Paper Trading og kontroll ikke faller tilbake til undermeny.",
    "Særskilt overvåking er flyttet ut av hovedbanner-menyen og har egen meny med banner, styring, tickerliste og fjerning.",
    "Særskilt-banneret bruker samme ticker-tape-struktur som hovedbanneret, med hastighet direkte på tracken.",
    "Ticker-banner-menyen gjelder nå bare hovedbannerets oppbygging, markeder, tickerlister og import.",
    "Paper Trading og kontroll bruker stabil tekstlabel uten emoji og fallback-rutingen åpner panelet for både gamle og nye labelvarianter.",
    "Særskilt overvåking vises igjen når banneret er aktivert, også når tickere bare har negativ ned-grense.",
    "Særskilt overvåking har administrasjon for å fjerne én ticker eller tømme listen.",
    "Særskilt overvåking bruker korrekt norsk tekst og dupliserer kortene nok til at banneret kan rulle også med kort liste.",
    "Synlige mojibake-rester i app.py er reparert til vanlig norsk tekst der de lot seg maskinelt rydde uten logikkendring.",
    "Banner- og kontrollsentertekst er strammet opp etter krasjfiksen, med mindre teknisk stoy i brukerflaten.",
    "Primary-, submit-, download-, link- og vanlige Streamlit-knapper bruker na en mer konsekvent kompakt og mork knappestil.",
    "Regresjonstestene kontrollerer at sentrale filer ikke har klassiske mojibake-rester.",
    "Bannervarsler normaliserer gamle positive ned-grenser til negative verdier, slik at AI Kontrollsenter ikke forsvinner under rendering.",
    "Rediger ticker-banner bruker ekte submit-knapp i Streamlit-formen og skal ikke lenger vise Missing Submit Button.",
    "Sarskilt overvaking har tydeligere pa/av- og hastighetskontroll i bannerinnstillingene.",
    "De mest synlige bannertekstene er ryddet for encoding-rot i denne flaten.",
    "Manuelle tickerlister i banneret har testbar parser for en ticker, flere tickere, komma, semikolon og linjeskift.",
    "Rediger ticker-banner har importseksjon for CSV eller innlimt tickerliste, med forhåndsvisning og valg for legg til eller erstatt marked.",
    "Oppfølgingsbanneret for særskilt overvåkning kan slås av/på og har egen hastighet, eller kan bruke hovedbannerets hastighet.",
    "Oppfølgingsbanneret bruker samme tickerkortstil og rullende animasjon som hovedbanneret.",
    "Felles dagsendring ned starter på 0 og kan reguleres til negative verdier med synlig minus.",
    "Paper Trading aksjekjøp har fått tilbake kjøpsbeløp, beregnet antall og beløpsstyrt manuelt paper-kjøp.",
    "Globale Streamlit-knapper, download-, link- og submit-knapper overstyres sent til kompakt stil for å hindre store blå felt i arbeidsflatene.",
    "Nordnet/manuell handel har versjonsført wrapper slik at tester og UI peker på samme arbeidsflate uten passordlagring eller ordreutsending.",
    "Ticker-banneret har klikkbare tickerkort som åpner større detaljvisning med kursgraf, MA50/MA200, 52-ukers høyde og volum mot 20/50-dagers snitt.",
    "Ticker-banneret har felles bannervarsler for viste markeder og individuelle tickervarsler for kurs, dagsendring og volum.",
    "Bannerkort viser grønne, gule og røde statusmarkører med opp/ned-retning for nær grense eller brudd.",
    "Bannervarsler og valutavarsler bruker tilbake-til-normal-logikk: samme brudd sender ikke nytt Pushover-varsel før verdien har vært innenfor grensen igjen.",
    "Bannervarsler har egen logg og valgfri Pushover-sending; standard er informasjonsmarkører uten Pushover-spam.",
    "Nordnet datatest er lagt inn som trygg forberedelse uten passordlagring og uten falsk livekobling.",
    "Marked og signaler er ryddet: Marked samler Rangering, Heatmap, Markedsklima, Lagrede signaler, IPO, Regime, Makro og Nyheter.",
    "Varsler og watchlist samler Varselsenter, Watchlist/signaler og Valutavarsler i ett brukerpanel.",
    "Varselsenteret viser lagrede varsler direkte og forklarer at nye skanninger skjer i kildemodulene.",
    "Intelligence og Heatmaps er merket som lagrede visninger, ikke egne markedsskannere.",
    "Services er skjult fra normal brukerflate og beholdes bare som teknisk fallback til senere cleanup.",
    "Legacy cleanup-plan er lagt til, slik at gamle kodebaner kan fjernes kontrollert etter egne tester.",
    "Paper Trading er omdøpt til Paper Trading og kontroll og samler simulert handel, beholdning, kontrollkort og regler på én side.",
    "Paper-portefølje kontroll er flyttet inn i Paper Trading-flaten og fjernet som separat synlig kontrollsenter-panel.",
    "Innkommende paper-hypoteser vises nå kollapset og skilles tydelig fra faktisk beholdning.",
    "Paper-posisjoner bruker kompakte Selg/Øk-handlinger og en mer moderne knappestil i stedet for dominerende fullbreddeknapper.",
    "Handelslogg og beholdningsoversikt bruker felles paper-kolonner med tid, status, ticker, marked, sektor, pris, antall, verdi, P/L, signal og forklaring.",
    "Login har Glemt passord-flyt med ADMIN_RESET_KEY, og reset_admin_password.py kan sette nytt passord lokalt når brukeren ikke kommer inn.",
    "Market Climate Explainability videreføres og utvides med grafarkiv og importerbare underlag.",
    "Markedsklima har fått graf- og tabellarkiv for egne/importerbare datasett, med status, nivåer, forklaring og rapport-/eksportstøtte.",
    "Manuelle klimaindikatorer har fått hurtiglenker til aktuelle kilder som SEC IPO statistics, AAII, MacroMicro og Brookings scenario-underlag.",
    "Grafarkivet kan importere CSV/XLSX/XLS og knytte filen til riktig graf, slik at tabellrader følger med i snapshot, CSV, JSON og Print/PDF HTML.",
    "Markedsklima viser nå egne arkivfaner for grafkilder, importformat, lavt/normalt/høyt nivå og tabell-/grafvisning av importerte underlag.",
    "Markedsklima viser nå tydelige lavt/normalt/høyt-nivåer, farger og teksttolkning for samlet klima og hver faktor.",
    "Markedsklima viser manuelle IPO-, pris/bok- og sentimentverdier med direkte nivåtolkning før snapshot lagres.",
    "Markedsklima-rapporten har nivåforklaring, lavt/normalt/høyt-tabeller, markedsgraf, indikatorgraf og print/PDF-vennlig HTML.",
    "AI Kandidattest viser Markedsklima ved kjøring som egen farget statusboks og flytter Klimanivå, Klimaeffekt og Klimatolkning tidlig i resultatlisten.",
    "AI Kandidattest-rapportene forklarer hvordan rødt/oransje klima gjør motoren strengere, og hvordan grønt klima kan gi litt mer rom til vekst og momentum.",
    "AI Kandidattest har egen Std klima-knapp for å nullstille bare markedsklima-effekt, cap og varselvalg til standard for valgt horisont.",
    "AI Kandidattest kan nå bruke Markedsklima som Av, Vis som info eller Bruk i score.",
    "Markedsklima kan gi en kontrollert positiv/negativ scorejustering og cappe kandidatscore når klimaet er svakt.",
    "AI Kandidattest-resultater viser Markedsklima, Klimamodus, Klimajustering og Klimabevis per kandidat.",
    "Datakildestatus viser siste Markedsklima-snapshot og varsler når klima mangler i stedet for å late som data finnes.",
    "CSV, JSON, detaljrapport og Print/PDF HTML tar med valgt klimamodus, klimaeffekt og faktorbevis.",
    "Markedsklima er lagt inn som egen modul i kontrollsenteret og under AI Kandidattest-gruppen.",
    "Markedsklima henter brede markedsproxyer, volatilitet, renter, Brent og USD/NOK via yfinance når brukeren trykker Oppdater klima.",
    "Markedsklima kan ta inn manuelle/importerte klimaindikatorer for USA IPO-antall, OSEBX pris/bok og bullish investorandel.",
    "Modulen lager samlet klima-score, confidence, faktorbevis, datamangler, normalisert markedsgraf og faktorgraf.",
    "Markedsklima lagrer siste snapshot via StorageService og tilbyr CSV, JSON og print/PDF HTML med grafer og tabeller.",
    "Markedsklima er gjort om fra en abstrakt score til en forklarbar beslutningsstøtte med nivåer, terskler, tabeller og grafer.",
    "AI Kandidattest har fått Financial Modeling Prep som valgfri ny ekstern live-kilde via FMP_API_KEY.",
    "FMP live kan brukes som egen kilde for bredere tickerunivers og som fersk signalberikelse for grovkandidater.",
    "FMP-adapteren henter og normaliserer analytiker-/estimatdata, price target consensus, earnings/resultatsjokk og insiderhandler.",
    "Live-signalmotoren kan nå kombinere Finnhub og FMP; manglende API-nøkkel vises som datastatus i stedet for å gi falske funn.",
    "AI Kandidattest-resultater og rapportfelt viser FMP-funn i Estimatgrunnlag, Insidergrunnlag, Resultatkalender, Ferske signalkilder og Signalstatus.",
    "Insider-score i AI Kandidattest bruker nå faktisk fersk insider_score når den finnes, slik at Finnhub/FMP-eiertrykk kan påvirke motoren riktig.",
    "AI Kandidattest kan nå berike grovkandidater med ferske AI-signaler fra eksisterende Finnhub-moduler når FINNHUB_API_KEY finnes: analytikerkonsensus, resultatkalender og insider.",
    "Analytiker-modulen leser nå miljø/secrets dynamisk via runtime_env, slik at .env-lastede FINNHUB_API_KEY-verdier faktisk brukes i appen.",
    "AI Kandidattest lagrer og viser Ferske signalkilder, Signalstatus, Estimatgrunnlag, Insidergrunnlag og Resultatkalender per kandidat.",
    "Estimat- og insider-signaler markeres som manglende når Finnhub-nøkkel eller konkrete treff mangler, i stedet for at nøytral standardscore fremstilles som funn.",
    "Resultatsjokk krever nå faktisk surprise, rapportert mot estimat eller guiding for å regnes som bekreftet; fremtidige estimater alene gir ikke lenger falskt bekreftet resultatsjokk.",
    "Rapport/HTML/JSON tar med fersk-signalstatus og konkrete signalfunn slik at utvelgelsen kan etterprøves bedre.",
    "AI Kandidattest viser nå Utvalgsgrunnlag, Bevisstatus og Prioritert bevis per kandidat, slik at grunnlaget for utvelgelsen blir synlig i prioritert rekkefølge.",
    "Resultatsjokk-søk skiller mellom bekreftet fundamentalt resultatsjokk og teknisk/proxy-basert reaksjon når EPS-, omsetnings- eller guidance-data mangler.",
    "Detaljrapport og Print/PDF HTML har en egen Hvorfor ble aksjen valgt-seksjon med prioritet, funn, verdi, poengbidrag, kilde, dato og status.",
    "Neste handling er strammet inn slik at kandidater med Unngå ikke samtidig foreslås sendt videre til vurdering eller paper trading.",
    "AI Kandidattest skjuler Plotly-verktøylinjen i teknisk detaljgraf, slik at zoom-knapper ikke dekker kurver eller nøkkeltall.",
    "Teknisk detaljgraf viser 52-ukers høyde og siste kurs som rene linjer med legend/tekst utenfor plotteflaten, slik at label-tekst ikke overlapper.",
    "Detalj Print/PDF HTML bygger nå printvennlige SVG-kurver for kurs, MA50/MA200, 52-ukers høyde og volum mot 20/50-dagers snitt.",
    "Detaljrapporten kombinerer skriftlige nøkkeltall, teknisk bevis og kurvebilder per valgt ticker i samme HTML/PDF-rapport.",
    "AI Kandidattest skiller nå tydelig mellom hovedsignalsøk og spesialsøk, slik at uavhukede signaler ikke ser ut som aktive i søkevektene.",
    "AI Kandidattest har kildestøtte-modus: Ingen, Vis som info eller Bruk som støtte i score.",
    "Rene Momentum/Estimat/Eiertrykk-søk viser bare aktive signalfamilier i resultatkolonnene; ubrukte signaler vises som strek.",
    "AI Kandidattest viser teknisk bevis med kurs, 52-ukers høyde, MA50/MA200, volum mot 20/50-dagers snitt, likviditet og benchmarkstatus i detalj/rapport.",
    "Detaljvisning for enkel ticker kan vise teknisk kurskurve med MA50, MA200, 52-ukers høyde og volum mot 20/50-dagers snitt når kursdata kan hentes.",
    "Valutavarsler har egen Send Pushover-test-knapp, mens grensesjekken heter Sjekk valutagrense nå og sender bare Pushover ved faktisk brudd.",
    "Pushover-testknappene tåler både gammel og ny notifier-returform og laster lokale miljøvariabler før tokenstatus kontrolleres.",
    "AI Kandidattest har mer kompakte handlingsknapper og avansert scoring kan skjules for bedre oversikt.",
    "AI Kandidattest har hard signalmodus: Momentum / relativ styrke, Estimatløft og Innsider / eiertrykk kan kjøres rent alene eller som manuell kombinasjon.",
    "AI Kandidattest har spesialsøk for Resultatsjokk, 52-ukers breakout, Volumbrudd, Vekstakselerasjon, Sektorleder, Short squeeze og Katalysator-klynge.",
    "Søkevekter i AI Kandidattest har en liten Std-knapp med standardfordeling for valgte hovedsignaler, mens spesialsøk viser egne ferdige vekter i rapporten.",
    "AI Kandidattest kan kjøres på enkel ticker og skanner et bredere eksplisitt kandidatgrunnlag før resultatlisten begrenses til valgt maks antall.",
    "AI Kandidattest sorterer resultatlisten etter ny søkescore og har detaljrapport for valgte kandidater eller enkeltticker med CSV, JSON og print/PDF HTML.",
    "AI Kandidattest-resultatet viser sektor, signalmodus, søkevekter, momentumscore, estimatløftscore, eiertrykkscore, volumbrudd og resultatsjokk der data finnes.",
    "Valutavarsler viser aktivt varsel, nåværende kurs, status, intervaller og kilde øverst før feltene, med kompakte Hent kurs nå og Sjekk varsel nå-knapper.",
    "Kontrollsenteret bruker en kompakt Lukk oppgave-knapp i stedet for en bred blå toppbannerknapp.",
    "AI Kandidattest har ekte tidshorisontvalg for 1-3 mnd, 1-6 mnd og 3-12 mnd; profilnavn er bare rapportetikett.",
    "AI Kandidattest bruker kildeferskhet i scoring: gamle eller udaterte NBIM/Folketrygdfondet-data vises som historisk støtte og gir ikke full rangeringseffekt.",
    "Kildevalg i AI Kandidattest er byttet fra åpen multiselect til faste avhukinger for Marked, Finansavisen, Oljefond/NBIM, Folketrygdfondet og Manuell liste.",
    "NBIM og Folketrygdfondet kan lagre kildedato/as-of ved import, slik at AI Kandidattest kan skille fersk evidens fra historisk støtte.",
    "Valutavarsler har livepanel for gjeldende Yahoo-kurs, separate valg for Sjekk hvert og Varselpause, og lagrer intervallene i minutter.",
    "AI Kandidattest har fått Standard 1-6 mnd signalprofil med justerbare vekter for relativ styrke, estimatendringer, insiderkjøp, omsetnings-/resultatvekst og teknisk trend.",
    "Evalueringsoppsett har egne sperrer og varsler for under 200-dagers snitt, under 50-dagers snitt, høy gjeld, fallende vekst, svak likviditet, gammel datakilde og for smalt signalgrunnlag.",
    "AI Kandidattest-resultatet viser delsignalene, sterke signaler, sperrer/varsler og datamangler per kandidat, og rapport/HTML dokumenterer samme metode.",
    "AI Kandidattest kan velge flere kilder samtidig til samme kjøring: Marked, Finansavisen, Oljefond/NBIM, Folketrygdfondet og Manuell liste.",
    "Evalueringsoppsett er lagt inn i AI Kandidattest med lagring, Bruk standard, justerbare kildebonuser, risikotrekk, confidencekrav og anbefalingsterskler.",
    "Rapport/print/PDF HTML og JSON tar med valgte kilder, evalueringsprofil og metodeforklaring for kjøringen.",
    "Kilder og import bruker én Velg kilde-dropdown i stedet for store blå kildeknapper.",
    "Folketrygdfondet skiller nå mellom xlrd for gamle .xls-filer og openpyxl for .xlsx-filer, slik at importfeil forklares riktig.",
    "AI Kandidattest er nå eneste synlige importsted for Finansavisen, Oljefond/NBIM og Folketrygdfondet.",
    "Kilder og import er flyttet inn som kildevelger i AI Kandidattest, slik at importerte data lagres ett sted og kan brukes av andre paneler ved behov.",
    "Separate menyvalg for Finansavisen, Oljefond Radar og Folketrygdfondet er skjult fra Kontrollsenteret; de gamle rendererne beholdes internt som trygg fallback.",
    "Folketrygdfondet har fått samme arbeidsmønster som de andre kildene: importer og lagre, søk/filter, tabell, CSV, JSON, print/PDF HTML, PDF og sending til AI Kandidattest.",
    "Folketrygdfondet kan lagre importerte rader selv når ticker-match er 0, slik at data ikke forsvinner når du bytter side.",
    "Ticker-banneret bruker lokal Lagre og bruk banner-knapp; endringer trigges ikke per felt og trenger ikke global oppdateringsknapp.",
    "Store globale Start/Pause/Stopp/Nødstopp-knapper er fjernet fra toppflaten og erstattet med kompakt Paper Trading-kontroll inne i Paper Trading.",
    "Marked/rangering kan hente tickere fra lagret AI-kildegrunnlag i stedet for gammel Dataunderlag-arbeidsflyt.",
    "Kilder og import erstatter Dataunderlag som synlig kildehub under AI Kandidattest.",
    "Den gamle arbeidsflytflaten med Test 1-10-status, pakkevisning og send-til-neste-test er fjernet fra synlig UI.",
    "Ingen valgt-radioknapper er fjernet fra Kontrollsenteret; lukk-knappen brukes for å lukke valgt oppgave.",
    "Folketrygdfondet er bygget ut med importer-og-lagre, status, CSV, JSON, Print/PDF HTML, PDF og sending til AI Kandidattest.",
    "Finansavisen og Oljefond/NBIM kan sende matchede tickere direkte til AI Kandidattest i stedet for gammel Test 2-flyt.",
    "AI Kandidattest er nå eget hovedvalg i Kontrollsenteret og åpner kandidatesten direkte.",
    "Dataunderlag, Aktørregister, Oljefond/NBIM, Finansavisen, Folketrygdfondet og Alpha Radar ligger samlet som kilder og støttepaneler under AI Kandidattest.",
    "Folketrygdfondet-importen er registrert i riktig menygruppe slik at XLS-knappen åpner importpanelet i stedet for å falle tilbake til start.",
    "Den gamle flyt-etiketten er erstattet av Analyseflyt i kontrollsenteret.",
    "AI Kandidattest er videreutviklet til kandidat-cockpit med Land, faktisk Marked, Bors og valgt Univers per rad.",
    "AI Kandidattest viser Kildestyrke, Endring fra forrige kjoring og en kort Forklaring per kandidat.",
    "AI Kandidattest har valg-tabell med avhuking og kan sende valgte kandidater til Top Picks, Beslutningsgrunnlag, Paper Trading eller Watchlist.",
    "Anbefalingene i AI Kandidattest bruker mer profesjonelle etiketter som Sterk kandidat, Vurder, Vent og Unnga.",
    "AI Kandidattest samler fersk kandidatfangst, importert kildeevidens, score, confidence, anbefaling og eksport i ett hovedpanel.",
    "AI Kandidattest lagrer siste analyseresultat og tilbyr CSV, JSON og printvennlig HTML som kan lagres til PDF.",
    "AI Kandidattest viser datakildestatus slik at ferske markedskjøringer skilles fra lokale importerte overlay-data.",
    "AI Kandidattest tilbyr eksport og printvennlig rapport også når en kjoring ender med 0 kandidater.",
    "Yfinance-cache legges i lokal arbeidsmappe for å unngå databasefeil ved webkjoring.",
    "Appen starter nå med Ingen valgt i Kontrollsenteret i stedet for å åpne Marked automatisk.",
    "Sidepanelets Visning-valg er fjernet fordi Kompakt og Full var like i praksis.",
    "Analyseflyt-hovedvalg med bare ett relevant panel åpner panelet direkte uten ekstra undermeny.",
    "Interaktiv ticker-input ryddes ikke lenger bort av gammel demo-/seed-cleanup.",
    "Test 1 behandler nå Finansavisen, Oljefond/NBIM og Folketrygdfondet som datakilder/overlays, ikke som rå filer som sendes gjennom hele Test 1-10-flyten.",
    "Folketrygdfondet har nytt importpanel for .xls/.xlsx som bygger institusjonelt eier-overlay til senere tester.",
    "Test 3 viser en aktiv Fortsett med rå input fra Test 2-knapp når Smart AI-filteret gir 0 funn, slik at Test 4 ikke blir visuelt skjult.",
    "Globale Streamlit-knapper er strammet ned til kompakt hoyde, mindre padding og mindre tekst.",
    "Tickeruttrekk fra Analyseflyt ignorerer nå metadatafelt som raw, score_parts og mangler-felt, slik at de ikke blir falske aksjesymboler i Test 3 og videre.",
    "Pipeline-pakker filtrerer bort ugyldige tickerverdier fra Test 2-10, men lar Dataunderlag fortsatt sende kontrollrapport uten aksjeticker.",
    "Store bla knapper er strammet til normal knappestorrelse globalt, med tekstbrytning for lange handlingsknapper.",
    "Finansavisen-import har bare avhuking for Aktorregister-synk; den dupliserte Synk lagret import-knappen er fjernet.",
    "Smart AI har bare en Kjor Smart AI-utvalg-knapp i selve Smart AI-utvalg-seksjonen; flytbaren viser status og viderevalg.",
    "Analyseunivers forklarer standardverdiene for Top Picks-score og momentum/strength-filter direkte ved sliderne.",
    "Kontrollsenteret viser en egen Analyseflyt-meny for aktivt steg, slik at relevante paneler/tester ligger samlet uten å blande inn alt annet som standard.",
    "Smart AI/Top Picks-resultater respekterer valgt maks-antall i stedet for skjulte 10/15-grenser.",
    "Fjernet den doble Start her: 1. Dataunderlag-knappen; Test 1-10-knappene er nå eneste pipeline-hurtigvalg.",
    "Finansavisen-knappene sier eksplisitt Test 2 Marked/rangering og bruker nye widget-nokler slik at gamle Streamlit-knapper ikke henger igjen.",
    "Direkte Test 8-valg fra Finansavisen kan nå velge alle matchede tickere i visningen, ikke et gammelt 20/60-tak.",
    "Alpha Radar-beslutningsvalg kan nå sende alle kandidater i resultatet videre til Beslutningsgrunnlag.",
    "Pipelinebaren kan nå sende rå input videre når en test har input men 0 funn, slik at flyten ikke stopper i Test 3-8.",
    "Input/output-tall viser effektiv input for Portefoljeanalyse og Paper Trading når resultatpakken allerede finnes.",
    "Alpha Radar og Early Warning V1 synker nå aktivt steg riktig i hovedflyten når du bytter sokemotor.",
    "Beslutningsgrunnlag kan sende rå analyseflyt-input videre til Portefoljeanalyse når vurderingen gir 0 output.",
    "Portefoljeanalyse viser posisjoner i tydelige kolonner med ticker, vekt, type, kategori, sektor, marked og detalj.",
    "Paper Trading viser mottatte kandidater fra Test 9 i en lesbar input-tabell før simulert handel.",
    "Test 3 viser nå en egen Videre til Test 4-blokk med valg for Smart AI-funn eller rå input fra Test 2.",
    "Send videre til Test 4 ligger ikke lenger i en smal kolonne som kan forsvinne visuelt når Test 3 har 60 inn og 0 ut.",
    "Finansavisen i Test 1 viser nå Input/Output for handler, matched tickere og valgt/hele dataunderlag.",
    "Finansavisen-knappene sender nå valgte tickere eller hele dataunderlaget til Test 2 Marked/rangering, ikke tilbake til samme Test 1-panel.",
    "Test 2 bruker inputpakken fra Dataunderlag når den finnes, i stedet for å ignorere den og hente første N fra felles univers.",
    "Direkte sending til Test 8 fra Finansavisen bruker valgt antall tickere i stedet for gammel skjult limit 20.",
    "Dynamiske analyseflyt-slidere nuller nå gamle session-verdier som ligger over ny inputpakke, slik at Test 4 ikke krasjer med 30 > 18.",
    "Test 2, Test 4, Test 7, Test 9 og Alpha/Early Warning har slider-guard mot gamle verdier når inputpakken blir mindre.",
    "Analyseunivers-tabeller har nå Vis antall rader 10/15/20/30/Alle, med Alle som standard når pakken er 60 eller mindre.",
    "Smart Universe Picker viser ikke lenger score-/styrke-/1M-/3M-kolonner før Smart AI faktisk er kjørt.",
    "Smart AI- og Picker-knapper sender valgt maks-antall videre, ikke gamle hardkodede 10/30-grenser.",
    "Eldre Top Picks-kodevei bruker valgt max_count i stedet for hardkodet 15.",
    "Smart AI-tabeller bruker visningsnummer i faktisk sorteringsrekkefolge, slik at gamle rank-tall ikke hopper i venstre kolonne.",
    "Test 3 har nå tydelig Kjor-knapp i flytbaren og en aktiv Fortsett med inputpakken-knapp når Smart AI-filteret gir 0 output.",
    "Fortsett med inputpakken lagrer Test 3-output som ufiltrert bypass og sender kandidatene videre til Test 4 uten automatisk tung analyse.",
    "Test 3 viser nå Forrige-knapp, tydelig Input/output-status og Send videre til Test 4 i samme flytbar.",
    "Analyseflyt input i Test 3 bruker hele mottatt kandidatpakke som standard og slideren kan ikke gå over antall kandidater fra Test 2.",
    "Manuell ticker og manuell liste skjules i Test 3 når valgt modus ikke bruker dem.",
    "Roadmap/detaljstatus i Analyseunivers er midlertidig gjort kompakt for å hindre stor hvit/tom flate.",
    "Test 3 lagrer nå Smart AI-output som pipeline-pakke og sender den videre til Test 4, slik at Top Picks mottar faktisk input i stedet for 0/0.",
    "Kandidat-slidere for analyseflyt-input låses til faktisk inputpakke, og rangeringsvisning kan velge Topp 10, 15, 20, 30 eller Alle uten å endre pakken som sendes videre.",
    "Pipeline-service har regresjonstest for hele dataflyten fra Test 1 Dataunderlag til Test 10 Paper Trading.",
    "Steg 1 heter nå 1. Dataunderlag, fordi det samler og kontrollerer underlag før Test 2 uten å kjøre analyse.",
    "Analyseflyten har hurtigtaster for Test 1-10, synlig aktivt steg, forrige/neste-knapper og bedre synk mellom aktivt panel og undermeny.",
    "Input/output-visningen forklarer input fra forrige steg og output fra dette steg, og Dataunderlag-output viser kontrollrapport i stedet for tom kandidatvisning.",
    "1. Dataunderlag er datakilde-cockpit med direkte knapper til Finansavisen, Aktørregister, Oljefond/NBIM og kildestatus.",
    "Test 2 Marked/rangering har Dataunderlag som standard univers, viser om input fra steg 1 er mottatt og forklarer hva universet bruker.",
    "Analyseflyt-statusen er ryddet til en hovedtabell og en lukket detaljvisning, slik at samme stegstatus ikke vises dobbelt.",
    "Pipeline-linjen i Test 2-10 viser nå forrige steg, input/output-status og send-videre-knapp; den gamle midtknappen for å åpne samme test med standardvalg er fjernet.",
    "Nytt Marked-rom samler marked, chart-valg, gruppering, periode og visning i en terminal-lignende toolbar med Oversikt, Rangering, Heatmap, Regime, Makro og Nyheter.",
    "Start/Pause/Stopp og Global oppdatering skjules bak drift-valg i sidepanelet.",
    "Husk-meg-token lagres i browser storage uten å bli liggende synlig som remember_token i adresselinjen.",
    "Test 3 Smart AI-filter velger Analyseflyt input automatisk når Test 2 har sendt kandidater videre, og videre-knapper viser antall kandidater som sendes.",
    "Test 2 Marked/rangering har synlig progress med faser for univers, data/cache, lagring og ferdig kandidatpakke.",
    "Tickerkort bruker felles metadata for firmanavn og har utvidet dekning for blant annet MO/Altria og AKAM/Akamai.",
    "Sidepanelet skiller nå tydeligere mellom vanlig visningsmodus og driftvalg for Start/Stopp/Global.",
    "Finansavisen-panelet kan sende importstatus tilbake til 1. Dataunderlag og hoppe dit, mens direkte snarvei til Beslutningsgrunnlag er merket som Test 8.",
    "Godkjenn og send til Test 2 ligger nederst etter datakildekontroll, ikke øverst før brukeren har sett hva som kan kontrolleres.",
    "Paper Trading fyller land, marked, sektor og bransje best-effort for gamle posisjoner/handler og lar posisjoner velges direkte til kjøp/salg.",
    "1. Dataunderlag ligger synlig under Marked og signaler med statusrad i AI Kontrollsenter.",
    "Paper Trading sjekker nå åpne posisjoner for stop-loss, take-profit, trailing stop og RSI-exit før nye BUY-signaler kan overstyre.",
    "Handelsloggen viser land, marked, sektor/bransje, regel, grense, målt verdi og en kort forklaring på hvorfor en handel ble gjort eller solgt.",
    "Analyseflyt starter med 1. Dataunderlag og veiviser videre til Test 10 Paper Trading.",
    "Hvert hovedsteg viser input/output-status, anbefalt standardvalg og knapp for å sende ferdig kandidatpakke videre uten automatisk tung kjoring.",
    "Veiviseren hopper til riktig Kontrollsenter-panel og setter Analyseflyt input der det er relevant, mens selve motorene fortsatt krever eksplisitt Kjor.",
    "Felles markedsvalg er videreført i AI Kontrollsenter, Top Picks, Smart Universe, banner og Fond/ETF.",
    "Finland, Danmark og Brasil er synlige valg der markedsmotoren brukes, mens Norden samler Norge, Sverige, Finland og Danmark.",
    "Smart Universe-tabeller viser selskap, land, børs, status, score, risiko og forklaring i stedet for bare ticker.",
    "Fond/ETF har marked/region, automatisk benchmark og tydelig melding når pris-/NAV-data mangler.",
    "Små tekster, statusrader og mørke tabeller er gjort mer lesbare på PC og mobil.",
    "Paper Trading viser aksjekjøp igjen, henter pris/NAV tydeligere og viser gjeldende trading-strategi.",
    "Mobil-login, Smart AI-statuskort og Analyseunivers-oppsett er forbedret for mindre friksjon.",
    "AI Kontrollsenter er gjort tydeligere som hovedarbeidsflate med større header og aktivt panel.",
    "Apne AI Kontrollsenter-linjen er gjort tydeligere og friskere, og importfeil i Kontrollsenter-header er rettet.",
    "AI Kontrollsenter-valgene er gjort lysere/storre, panelvalg synkroniseres med arbeidsomrade, og Paper Trading nullstiller gammel pris ved tickerbytte.",
    "Paper Trading bruker markedsmotoren til prisforslag/system-confidence og viser posisjonsgevinst/-tap i tydelige blå/rode kort.",
    "Strategi-test Pro har tryggere kraftig smart-test, tydeligere tidlig stopp og hopper over enkeltkombinasjoner som feiler.",
    "AI Kontrollsenter-valgene er rendret som tydeligere blå kontrollbokser, og den lille dupliserte toppstripen er fjernet.",
    "P/E vises i Top Picks/hurtigkort i tillegg til detaljanalysen, basert på forward/trailing P/E fra felles aksjeanalyse.",
    "Learning history skjuler demo-/testtickere fra brukerlisten og viser tolkning av retning, prognosebånd og snittfeil.",
    "Topplinjen er ryddet for sesjonschips som Manuell, Bruker og Husk meg.",
    "Heatmap filtrerer bort gamle AAPL/STB.OL-seeddata og bruker samme filtrerte datasett for tall og visning.",
    "Tekniske kursnivaer viser valuta tydeligere, ORK/ORKLY tolkes som ORK.OL, og chart/legend-spacing er forbedret.",
    "Regime-panelet har markedvalg for USA, Norge, Sverige, Danmark, Finland, Brasil og Norden.",
    "Paper Trading-portefoljen kan brukes som testarena for portefoljeovervaking, kontrollpunkter og AI-forslag.",
    "AI Kontrollsenter har valutavarsler med faste ovre/nedre grenser og Pushover-stotte, for eksempel BRL/NOK.",
    "AI Kontrollsenter har hovedboks-rad, automatisk undermeny, favoritter, sist brukt, sok, arbeidsmodus og paneltellere.",
    "AI Kontrollsenter bruker ren hurtignavigasjon uten skjulte gamle dropdowns, med tydelig Til hovedvalg-knapp.",
    "AI Kontrollsenter er forenklet til hovedbokser og kompakt undermeny, uten automatisk åpnet startpanel.",
    "AI Kontrollsenter bruker stabil radio-basert hovedmeny og undermeny for mindre knekk ved menyvalg.",
    "AI Kontrollsenter-navigasjon unngår ekstra rerun og hopper over ticker-banneret under aktiv menybruk.",
    "Gamle AAPL/MSFT/NVDA-defaults er fjernet fra Daily Report, Prognose og service-univers, og tester stopper skjult manuell fallback.",
    "Regresjonsvern er utvidet for kildeprioritet, panel-smoke, tung-jobb gating og visuelle statiske guardrails.",
    "Oppstart av Kontrollsenter nuller engangsflagget for tung jobb slik at ticker-banneret ikke forsinker Analyseunivers/preview.",
    "Analyseunivers forklarer tydelig forskjellen mellom tickerliste/univers, preview-cache og scorede Smart AI-kandidater.",
    "AI Kontrollsenter har Alpha Radar som eksplisitt kjørt hypotesemotor for 1-15 mulige aksjecaser på 1, 3, 6 og 12 måneder.",
    "Alpha Radar V2 bruker Contrarian / Hidden Potential Score med underdekkethet, vendepunkt, insider/bjellesauer, uvanlig volum, ravare/makro, why-now og crowding-straff.",
    "Alpha Radar har strengere parameterdisiplin med harde borsverdi-gates, presisjonsvalg, lav-data blokkering og tydelige ekskluderingsårsaker.",
    "Alpha Radar viser scan-progresjon, skiller signal-lupe fra datakilder, markerer gamle resultater når input endres og kan lagre/eksportere resultat.",
    "Alpha Radar viser manglende faktorgrunnlag som N/A, stopper univershenting ved vanlige menyvalg, har komplett print/Excel-eksport og Early Warning V1.",
    "Early Warning er skilt tydeligere fra Alpha Radar med ferske kildebevis, insider-/bjellesau-spor, nyhetskatalysatorer og Euronext/Norden-notat i rapportene.",
    "Alpha Radar/Early Warning-rapportene viser kildespor med titler, kilder, datoer og lenker der datakilden leverer dette.",
    "Mobilvisning for driftkontroll og Alpha Radar Signal-lupe er strammet inn uten å flytte tunge jobber ut fra eksplisitte Kjor-knapper.",
    "Alpha Radar og Early Warning bruker felles regelmotor for Signal-lupe, datakilder, låsing, lav-data og overstyringsrekkefolge.",
    "Radar-panelet viser Kjoringsbudsjett / Run Preview med 0 tunge kall ved menyvalg og planlagt kostnad ved Kjor.",
    "Neste GO: hvis appen fortsatt dimmer ved menyvalg, profiler hele Kontrollsenter-renderen og flytt gjenvaerende cache-/statuskall ut bak eksplisitte knapper.",
    "Radar-menyene er strammet: Radar-modus låser kjerne-signalene, ekstra Signal-lupe er separat, og datakilder folger samme regelmodell.",
    "Insider-modus i Alpha Radar starter nå med Insider/bjellesauer alene; nyheter/resultater blir kun stottevalg hvis bruker legger dem til.",
    "Kontrollsenter avslutter tung-jobb-gaten før st.stop, slik at Global oppdatering ikke blir hengende igjen og gjør senere menyvalg tunge.",
    "Alpha Radar og Early Warning henter alltid ferskt run-univers ved Kjor, nuller gammel tickerliste og viser markedstelling for univers, skannet, scoret, ekskludert og funn.",
    "Alle/Norden bruker balansert sluttliste: beste funn per marked tas med før resten fylles etter score, slik at USA ikke kan skjule alle andre markeder uten forklaring.",
    "Funn-grensen er utvidet til 60 for brede univers, og IPO/pre-IPO forklares som separat område, ikke som skjult tillegg i 177-universet.",
    "Radarene krever nå konkret nyhets-/makro-/resultatevidens før faktorer merkes ekte, slik at tomme kildesøk ikke gir lik 45.0-katalysator på alle tickere.",
    "Borsverdi vises med punkt som tusenskille og lokal valuta, med ca. NOK-estimat der valuta ikke er NOK.",
    "Enkeltmarked bruker egen skannegrense i Alpha Radar/Early Warning, Brasil-listen er utvidet, og 177 behandles ikke som fast globalt tak.",
    "Alpha Radar og Early Warning skiller nå Insider fra Bjellesau i scoring, kildespor, CSV, Excel, HTML/PDF og resultatkort.",
    "AI Kontrollsenter har nytt Beslutningsgrunnlag-panel som tar radarfunn videre til manuell Kjop nå/Vent/Unnga-vurdering uten automatisk handel.",
    "Finnhub- og NewsAPI-nokler lastes nå robust fra work_d/.env eller work_d/.env/.env, og radarene viser trygg datakilde-status uten å vise nokler.",
    "Alpha Radar/Early Warning lar 1, 3, 6 og 12 mnd styre datavinduet for insider, nyheter og earnings, og har egen markedstest for USA/Norden-datakilder.",
    "Datakilde-status viser nå API-nokler i aktivt miljo uten å hevde at .env mangler, og lange kildefeil komprimeres i kandidatkortene.",
    "Aktørregister lar deg redigere bjellesauer/institusjoner/insider-watch med alias per marked, og radarene bruker dette til å merke aktorspor.",
    "Norden/Brasil får lokale kildediagnostikk-lenker for insider, flagging, borsmeldinger, OAM og katalysator-sok der globale API-er ikke dekker markedet.",
    "Early Warning bruker resultat-/vendepunkt-proxy når earnings/revisions mangler, og rapportene viser tydeligere datadiagnostikk for tomme felt.",
    "Oljefond Radar kan importere NBIM CSV, finne nye/okte/reduserte/solgte posisjoner og sende NBIM-spor videre til Beslutningsgrunnlag.",
    "Beslutningsgrunnlag har tydeligere knapper: Vurder hele køen og Tøm kø.",
    "NBIM-parseren leser nå ekte eq_YYYYMMDD.csv fra Oljefondet i UTF-16/semikolon-format og matcher selskapsnavn/land mot tickerregisteret.",
    "Tickeruniversene er utvidet for USA, Norge, Sverige, Finland, Danmark og Brasil, og run-preview sier tydelig når universkilden er mindre enn maks scan.",
    "Aktørregisteret har import/eksport for CSV/JSON, relevante tickere og NBIM/Oljefondet som aktiv institusjonell aktor.",
    "Radarene kan bruke finans-/offisiell sokelag ved Kjor, med aktornavn, alias, ticker, selskap og marked, uten tunge kall ved menyvalg.",
    "NBIM, finanssok, aktorregister og konkrete insider-/bjellesau-spor sendes videre til Alpha Radar, Early Warning, rapporter og Beslutningsgrunnlag.",
    "Oljefond Radar har prioriterte visninger for topp signaler, største beholdninger, nye kjøp, økninger, reduksjoner med restverdi, solgt ut, ticker-match og land/sektor.",
    "NBIM-tabeller viser markedsverdi med punkt som tusenskille og enhet, og previous/current value oversettes per metric til prosent, aksjer eller valuta.",
    "Oljefond Radar har progress-status fra filventing til ferdig analyse, uten nye nettverkskall eller meny-tungkjøring.",
    "NBIM Signal Lab finner overbevisning, akkumulering i svakhet, hoy eierandel, stemmerett-avvik, unmatched verdi, radar-overlap og watchlist-kandidater.",
    "NBIM land-/sektorrotasjon viser inn/ut/blandet, ny verdi, okt verdi, redusert restverdi og tidligere solgt-ut verdi.",
    "Alpha Radar og Early Warning bygger nå en felles Evidence Ledger per ticker med kilde, type, dato, aktor, styrke, lenke og funnet-av.",
    "Nordic Actor/Insider Search lager gratis/offisielle sokelenker for Norden og bruker Aktorregisteret automatisk ved insider-/bjellesau- og nyhetssok.",
    "Run Preview viser kildebudsjett/kildekø med NewsAPI, Finnhub, cache, aktørregister og gratis/offisielle søk før Kjør.",
    "Aktorregisteret har legg-til, slett-valgte, marked-dropdown, teksttest og Unmatched Workbench for navn som må kobles til alias.",
    "Aktorregisteret støtter flere roller per aktør, slik at samme person kan være Bjellesau og Insider watch uten dobbeltregistrering.",
    "Aktorregisteret har søk, sortering, hurtigredigering, alias-forslag, duplikatsjekk, tillitsnivå og lokal trefflogg per aktør.",
    "Radarene tolker aktørroller strengere: bjellesau-/institusjonsroller går til bjellesau-score, insider-watch/styre/ledelse går til insider-spor.",
    "Aktorregister-panelet viser tydelig at registeret lagres lokalt, men at navn/alias kan inngå i søk når bruker trykker Kjør.",
    "Radarene har harde bevisporter: velges insider/bjellesau og nyheter som kriterier, blir tickere uten konkrete kildespor ekskludert i stedet for å fylle topp 30.",
    "Aktørstyrt søk kjøres først og kan bruke gratis open web via GDELT/Google News RSS som supplement til NewsAPI, slik at lokale finansnyheter og aktørnavn faktisk kan gi treff.",
    "Aktørregisteret bruker lett tabell pluss enkelt skjema for ny/redigert aktør, med flerroller og trefflogg bak knapp for å unngå tung meny-rendering.",
    "Finansavisen Bjellesauer har egen lokal XLSX-import for 1D/1M/3M/6M/ALLE, deduplisering, periodescoring, rapport, eksport og Aktorregister-synk.",
    "Alpha Radar og Early Warning bruker Finansavisen-snapshot som billig lokalt bjellesau-evidenslag ved Kjor, uten Excel-parse eller nye nettverkskall ved menyvalg.",
    "Norske bjellesau-tickere som NORBIT, Zaptec og Axactor er lagt inn i ticker-/aliasregisteret slik at importerte handler kan treffe radaruniverset.",
    "Finansavisen-importen bruker filnavn og filstorrelse i periodevalg, slik at 1D/1M/3M/6M/ALLE ikke arver gamle valg.",
    "Finansavisen-deduplisering tåler overlappende filer i ulik rekkefolge og beholder alle kildeperioder uten importkrasj.",
    "Finansavisen Bjellesauer ligger under Marked og signaler, og Andre paneler skjules når ingen reelle restpaneler finnes.",
    "Finansavisen Bjellesauer har lesbar rapportseksjon, print/PDF-HTML, nedlastbar PDF, ticker-match-filter og sending til Beslutningsgrunnlag.",
    "Finansavisen Bjellesauer viser nå aksjedetaljer per dato, person og transaksjonslinje, og rapport/PDF tar med detaljene for viktige aksjer.",
    "Portefoljeanalyse analyserer Paper Trading-portefoljen komplett uten maksposisjon-slider og retter _clamp-krasjen.",
]

def get_app_version():
    return APP_VERSION

def get_app_build_label():
    return APP_BUILD_LABEL

def get_app_version_label():
    return APP_BUILD_LABEL

def get_app_patch_notes():
    return list(APP_PATCH_NOTES)


